version: '3.2'
services:
    config-server:
        container_name: config-server
        image: config-server
        ports:
            - "8000:8000"
        
        environment:
            - config.server.git.username=snitavets.ilya@gmail.com
            - config.server.git.pass=GitMzrs56@Hub18?7
            - eureka.server.host=sd-amp
            - eureka.server.port=8001

    sd-amp:
        container_name: sd-amp
        image: sd-amp
        ports:
            - "8001:8001"
        
        environment:
            - config.server.host=config-server
            - config.server.port=8000

        volumes:
            - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh

        command: 
            - /usr/local/bin/wait-for-it.sh
            - config-server:8000
            - --
            - usr/bin/java
            - -jar
            - /opt/lib/sd-amp.jar