server:
  port: 8001

spring:
  application:
    name: sp-amp

eureka:
  instance:
    hostname: localhost

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #should automatic fetch envs from this file
      defaultZone: http://localhost:8001/eureka/